version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build-and-test:
    executor: 
      name: node/default
    steps:
      - run: npm install
      - run: npm test
      - run: echo "This is a NEW STEPPPP"



workflows:
  build-and-test:
    jobs:
      - build-and-test
         
